.TH "App" 3 "Tue Feb 1 2022" "Java project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConvert\fP"
.br
.ti -1c
.RI "class \fBGui\fP"
.br
.ti -1c
.RI "class \fBLogin\fP"
.br
.ti -1c
.RI "class \fBSerialPortClass\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Java project from the source code\&.
