.TH "App.Login" 3 "Tue Feb 1 2022" "Java project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App.Login
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogin\fP ()"
.br
.ti -1c
.RI "boolean \fBtryToLogIn\fP (String login, String password)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "App\&.Login\&.Login ()"
Konstruktor bezparametrowy
.SH "Member Function Documentation"
.PP 
.SS "boolean App\&.Login\&.tryToLogIn (String login, String password)"
Metoda sprawdzająca poprawność wprowadzonych danych logowania\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Java project from the source code\&.
