.TH "App.Gui" 3 "Tue Feb 1 2022" "Java project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App.Gui
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGui\fP ()"
.br
.ti -1c
.RI "void \fBsendData\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Logger \fBgetLOGGER\fP ()"
.br
.RI "instancja Logger - tworzenie logów "
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "App\&.Gui\&.Gui ()"
Konstruktor \fBGui\fP Klasa główna, implementująca funkcjonalność logów, timera, portu szeregowego\&.
.SH "Member Function Documentation"
.PP 
.SS "static Logger App\&.Gui\&.getLOGGER ()\fC [static]\fP"

.PP
instancja Logger - tworzenie logów 
.SS "static void App\&.Gui\&.main (String[] args)\fC [static]\fP"
Główna metoda aplikacji Uruchamia program oraz tworzy podstawowy model GUI
.SS "void App\&.Gui\&.sendData ()"
Metoda wysyłająca dane do klasy SerialPort

.SH "Author"
.PP 
Generated automatically by Doxygen for Java project from the source code\&.
