.TH "App/Convert.java" 3 "Tue Feb 1 2022" "Java project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App/Convert.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\&.Convert\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBApp\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Java project from the source code\&.
